sudo: required
language: python
services:
- docker
script:
- export FULL_IMAGE_NAME=docker.io/halotools/python-sdk
- docker build --build-arg SDK_BRANCH=${SDK_BRANCH} -t python-sdk:latest -f dockerfiles/${DOCKERFILE}
  .
- export IMAGE_TAG=${DOCKERFILE}_sdk-${SDK_VERSION}
- export IMAGE_TAG_DATE=${IMAGE_TAG}_`date "+%Y-%m-%d"`
- docker tag python-sdk:latest ${FULL_IMAGE_NAME}:${IMAGE_TAG}
- docker tag python-sdk:latest ${FULL_IMAGE_NAME}:${IMAGE_TAG_DATE}
after_script:
  - docker images
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
  - docker push ${FULL_IMAGE_NAME}:${IMAGE_TAG}
  - docker push ${FULL_IMAGE_NAME}:${IMAGE_TAG_DATE}
env:
  matrix:
  - SDK_BRANCH=master SDK_VERSION=latest DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.1.2 SDK_VERSION=1.1.2 DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.1.1 SDK_VERSION=1.1.1 DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.1 SDK_VERSION=1.1 DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.0.6 SDK_VERSION=1.0.6 DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.0.5 SDK_VERSION=1.0.5 DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.0.4 SDK_VERSION=1.0.4 DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.0.3 SDK_VERSION=1.0.3 DOCKERFILE=ubuntu-16.04
  - SDK_BRANCH=v1.0.1 SDK_VERSION=1.0.1 DOCKERFILE=ubuntu-16.04
  global:
  - secure: eoAP0EOb4HGOxBV2jK2T2dY2hpnLnkOhKhMmWmBOMSRQrYkUnaxnV3Dng7lmiVhDToEdIbk4rZiOl3fdlItCISBjvCpfUXeSzjySSI9MQmVsFFXuk6Is5HTYuOr4KLohfP2+ZeRMvsEBTXuLqFVphjd7xashkkTbpC7JchdayIjgy3AZKK1OudTiksZwXy+aJGbqPXKwVC64Vhkz1zqb1+Bv4MqrreDLYbO96GVUNyr6lM8kEnNn/eIgaLvddR8VjdxnJ1h7a5kHn+LQy2ZsdxkwkyBR46UBNgT73NHZwcDGjYGeLtlGSeZ91urwAVolBmucteERzHf1ihjv/UryrsTU24UDjihxQtKneYIlh0T2UtM3d8Ib3TTZlDSX9aRFgZmjv8KcJs9mU5NUzAndi+JtWc3iKGWrX+MG/4bKwYcaSdr34b3mKd6dFyccPvdvmR9SUfai13QaiRjv5Mgc8aVnn5bCTt9ZYilzSn0gZa1uTIH4WHlT1dCZmS1l/zwnVYrhwp7Vhq2gmQe9kh8G4Q78bb3qflYx3vSheKm3/ea4KfnexPuef/9IeeenmHsOjipTA/R9BSttkLgZkcOyVsSN/a5Vw1NeNFSCErVQvAARZGQYo/QP9TtPhEgj5yGrgvhWKT5BVcaE9zLi8Q34PRy11ac7Qscrr1byUccM4cY=
  - secure: WDRLfIeuc7QXtEsU7kfIEUMhj65gjLFQ4KYezgmxhs7OQ/CnDdVAuwjKYIuGLollEG4c3OljmNHA0kQ5A7N08yanuaiYCH37Uf8i9amx6/43zl8bGtmuAMSup2T241DDDoYzf9I5VsWfTM5uWbv5Aocg2c9289F+jt7N3h+mYr4UspqAABphB6TRtAbJRIVS7m2A5n99d475fkEXQofISMmj5xmkLMHkWeeOt3K0omKkMKE3uv6h9VnT1nMUB66CsnPQQcowSBl6oSC5CyNGSDx3JGF0js/xDDcSDXQzChB5Zk+Ll71ZawjRZD0N2AsBlFBjFgFowCRsbh/UXrPl5ntUv8WD8USXyaHIeiSis+qG/ZMznefb+1ObgmBDEUznD+56y9wze7+cfFh6e5CyiwOt/qxdYK4bLcsYXoZyUQlLbwipSmcLhooGpl4+uuqn0+Q5i8m1bXq5g/K690CPi5s9dgQEQPlvyel5yl6PgZaROrunzylfxFdT0pS+uK51dMlrn4FsIRibJPEtmUCJzVyVY+BI1UI3qCulmcUqBd7c+UcNS/+vnNokaszLg+SdKFe6ovXKyIcgFbl82kuQu5/xgZTHwHupZRTykK3p+n8mQlNNl4IZHTpD+9wuisMfNO9hGt62oxPWpF9JIHHqzXjFYUvxU38sz5SuXEEiyc0=
